[project]
name = "condif2css"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "lxml>=5.3.0",
    "mvin>=0.5.0b4",
    "openpyxl>=3.1.5",
]

[tool.pyright]
venvPath = "."
venv = "venv"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]
